import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manually defined sidebar for consistent ordering
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/providers',
        'guides/modes',
        'guides/workflows',
        'guides/custom-providers',
        'guides/custom-modes',
        'guides/custom-workflows',
        'guides/knowledge',
        'guides/multimodal',
        'guides/cli',
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      items: [{type: 'autogenerated', dirName: 'tools'}],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
    {
      type: 'category',
      label: 'Migration',
      items: [{type: 'autogenerated', dirName: 'migration'}],
    },
  ],
};

export default sidebars;
