import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Manually defined sidebar for consistent ordering
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/providers',
        'guides/modes',
        'guides/workflows',
        'guides/custom-providers',
        'guides/custom-modes',
        'guides/custom-workflows',
        'guides/custom-tools',
        'guides/multimodal',
        'guides/hitl-confirmation',
        'guides/mcp-server',
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      items: [{type: 'autogenerated', dirName: 'tools'}],
    },
    {
      type: 'category',
      label: 'Knowledge Package',
      items: ['guides/knowledge'],
    },
    {
      type: 'category',
      label: 'Agents Package',
      items: [
        'agents/README',
        'agents/agents',
        'agents/channels',
        'agents/interceptors',
        'agents/conversation-history',
        'agents/capabilities',
        'agents/human-in-the-loop',
        'agents/registry',
        'agents/transport',
        'agents/testing',
        'agents/examples',
      ],
    },
    {
      type: 'category',
      label: 'CLI',
      items: ['guides/cli'],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],
};

export default sidebars;
